name: 'ffmpeg build Windows'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  uploaddependencies:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
 
    - name: Dump dependencies artifact_sha1
      shell: bash
      run: |
        mkdir artifact_sha1
        echo $GITHUB_SHA > artifact_sha1/sha

    - name: 'Upload artifact_sha1'
      uses: actions/upload-artifact@v2
      with:
        name: artifact_sha1
        path: artifact_sha1

    - name: Dump dependencies artifact_ffmpeg
      shell: bash
      run: |
        git clone --depth 1 https://github.com/Microsoft/vcpkg
        cd vcpkg
        ./bootstrap-vcpkg.bat -disableMetrics
        vcpkg install pthread:x64-windows ffmpeg:x64-windows
        vcpkg integrate install
 
    - name: 'Upload artifact_ffmpeg'
      uses: actions/upload-artifact@v2
      with:
        name: vcpkg
        path: D:\a\sxplayer\sxplayer\vcpkg
