name: 'tests Linux'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:

  Install dependencies:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
        sudo apt -y install meson ninja-build
        sudo apt -y install libglfw3-dev libglew-dev
        sudo apt -y install libavcodec-dev libavutil-dev libavformat-dev libavdevice-dev libavfilter-dev libswscale-dev libswresample-dev libpostproc-dev
        sudo apt -y install valgrind

  linux:
    runs-on: ubuntu-20.04
    needs: [Install dependencies]
    steps:
      - run: |
        meson setup --buildtype release builddir
        meson test -C builddir -v

  linux memory:
    runs-on: ubuntu-20.04
    needs: [Install dependencies]
    steps:
      - run: |
        meson setup --buildtype debugoptimized builddir-memory
        meson test --wrapper valgrind -C builddir-memory -v
