name: 'tests Windows VS'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  windows:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2

    - uses: msys2/setup-msys2@v2
 
    - name: install vcpkg
      shell: bash
      run: |
        choco install pkgconfiglite 
        pkg-config --variable pc_path pkg-config
        env::var("PKG_CONFIG_PATH")
        $env:PKG_CONFIG_PATH = "C:$env:HOMEPATH\AppData\Local\Programs\radare2\lib\pkgconfig"
        env::var("PKG_CONFIG_PATH")
