name: 'tests Windows VS'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  windows:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2 
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: install dependencies
      shell: bash
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat -disableMetrics
        vcpkg install pthread:x86-windows ffmpeg[ffmpeg,ffplay,nonfree,avresample]:x86-windows
        pip install meson      
        vcpkg integrate install
        vcpkg integrate project       
        find . -name '*ffmpeg*'
        find . -name '*avcodec*'
        find . -name '*pthread*'
        find . -name '*.pc*'
        find . -name '*.include*'
        find . -name '*.lib*'
    - name: Setup
      shell: cmd
      run: | 
        set INCLUDE=D:\a\sxplayer\sxplayer\vcpkg\installed\x86-windows\include;%INCLUDE%
        set LIB=D:\a\sxplayer\sxplayer\vcpkg\installed\x86-windows\lib;%LIB%
        set LIB=D:\a\sxplayer\sxplayer\vcpkg\packages\ffmpeg_x86-windows\lib;%LIB%
        set PKG_CONFIG_PATH=D:\a\sxplayer\sxplayer\vcpkg\installed\x86-windows\lib\pkgconfig;%PKG_CONFIG_PATH%
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" && meson setup builddir --backend vs 
  
    - name: BUILD
      shell: cmd
      run: |
        set PLATFORM="" 
        set INCLUDE=D:\a\sxplayer\sxplayer\vcpkg\installed\x86-windows\include;%INCLUDE%
        set LIB=D:\a\sxplayer\sxplayer\vcpkg\installed\x86-windows\lib;%LIB%
        set LIB=D:\a\sxplayer\sxplayer\vcpkg\packages\ffmpeg_x86-windows\lib;%LIB%
        set PKG_CONFIG_PATH=D:\a\sxplayer\sxplayer\vcpkg\installed\x86-windows\lib\pkgconfig;%PKG_CONFIG_PATH%
        set PATH=D:\a\sxplayer\sxplayer\vcpkg\packages\ffmpeg_x86-windows\lib;%LIB%
        set PATH=D:\a\sxplayer\sxplayer\vcpkg\installed\x86-windows\lib;%LIB%
        set VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2019
        cp D:\a\sxplayer\sxplayer\vcpkg\installed\x86-windows\bin\avcodec-58.dll D:\a\sxplayer\sxplayer\builddir\
        cp D:\a\sxplayer\sxplayer\vcpkg\installed\x86-windows\bin\avformat-58 D:\a\sxplayer\sxplayer\builddir\
        cp D:\a\sxplayer\sxplayer\vcpkg\installed\x86-windows\bin\swresample-3.dll D:\a\sxplayer\sxplayer\builddir\
        cp D:\a\sxplayer\sxplayer\vcpkg\installed\x86-windows\bin\avutil-56.dll D:\a\sxplayer\sxplayer\builddir\
        cp D:\a\sxplayer\sxplayer\vcpkg\installed\x86-windows\bin\avfilter-7.dll D:\a\sxplayer\sxplayer\builddir\
        cp D:\a\sxplayer\sxplayer\vcpkg\installed\x86-windows\bin\swscale-5.dll D:\a\sxplayer\sxplayer\builddir\
        cp D:\a\sxplayer\sxplayer\vcpkg\installed\x86-windows\bin\postproc-55.dll D:\a\sxplayer\sxplayer\builddir\
        cp D:\a\sxplayer\sxplayer\vcpkg\packages\pthreads_x86-windows\bin\pthreadVC3.dll D:\a\sxplayer\sxplayer\builddir\
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" && meson compile -C builddir -v
    
    - name: TEST
      shell: cmd
      run: |
        meson test -C builddir
 