name: 'tests Windows'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build_libs:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - uses: msys2/setup-msys2@v2

    - name: install vcpkg
      run: |
        C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm gcc pkg-config diffutils coreutils meson tar"

    - name: install vcpkg
      shell: bash
      run: |
        set VCPKG_DEFAULT_TRIPLET=x64-windows      
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat -disableMetrics
        vcpkg install ffmpeg[ffmpeg,ffplay,nonfree,avresample]:x86-windows-static
        vcpkg list
        pip install meson 
        cd ..
        VSINSTALLDIR="C:\Program Files (x86)\Microsoft Visual Studio\2019" meson setup builddir --backend vs

