name: 'tests Windows'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build_libs:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare vcpkg
        uses: lukka/run-vcpkg@v2
        id: runvcpkg
        with:
          vcpkgArguments: libarchive[core] openssl sqlite3
          vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
          vcpkgGitCommitId: ffa7fd27cfa29f206d1fd2ccfc722cad4aaeef3d
          vcpkgTriplet: x64-windows

          