name: 'tests Windows VS'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  windows:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2

    - uses: msys2/setup-msys2@v2
 
    - name: install vcpkg
      shell: cmd
      run: |
        echo %PKG_CONFIG_PATH%
  
        