name: 'tests Windows VS'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  windows:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2 
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
 
    - name: install vcpkg
      shell: cmd
      run: |
        pip install meson
        meson init --language=c --name=myproject --version=0.1
        meson setup builddir --backend vs  --buildtype plain --errorlogs -v  
        ls
        cat D:\a\sxplayer\sxplayer\build\meson-logs\meson-log.txt