name: 'tests Windows VS'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  windows:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2 
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: msys2/setup-msys2@v2

    - name: install dependencies
      shell: bash
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat -disableMetrics
        set(VCPKG_TARGET_ARCHITECTURE x64)
        set(VCPKG_CRT_LINKAGE dynamic)
        set(VCPKG_LIBRARY_LINKAGE dynamic)
        set(VCPKG_PLATFORM_TOOLSET v140)
        