name: 'tests Windows VS'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build_libs:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
      
      - name: Run a one-line script
        run: C:\msys64\usr\bin\bash -lc "D:\a\sxplayer\sxplayer\windows.sh"


          
