name: 'tests Windows VS'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  windows:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2 
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: install dependencies
      shell: bash
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat -disableMetrics
        vcpkg install ffmpeg[ffmpeg,ffplay,nonfree,avresample]:x86-windows-static
    
    - name: install vcpkg
      shell: cmd
      run: |
        pip install meson ninja
        set PKG_CONFIG_PATH=D:\a\sxplayer\sxplayer\vcpkg\installed\x86-windows-static\lib\pkgconfig;%PKG_CONFIG_PATH%;
        set VSCMD_DEBUG=3
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" && meson setup builddir --backend vs && meson compile -C builddir && meson test -C builddir 