name: 'tests Windows VS'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  windows:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2 
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

 
    - name: BUILD
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

    - name: TEST
      shell: cmd
      run: |
        meson test -C builddir