name: 'tests Windows VS'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  windows:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2 
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: install dependencies
      shell: bash
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat -disableMetrics
        vcpkg install ffmpeg[ffmpeg,ffplay,nonfree,avresample]:x86-windows-static
        pip install pthread

    - name: vscommand
      shell: cmd
      run: |
        set VSCMD="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"

    - name: Setup
      shell: cmd
      run: |
        VSCMD && meson setup builddir --backend vs --pkg-config-path "D:\a\sxplayer\sxplayer\vcpkg\installed\x86-windows-static\lib\pkgconfig"
      
    - name: Build
      shell: cmd
      run: |
        set PLATFORM="nothing"
        VSCMD && meson compile -C builddir -v

    - name: Test
      shell: cmd
      run: |
        VSCMD && meson test -C builddir

 