name: 'tests Windows'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build_libs:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Windows_Meson_Testlog
        path: build/meson-logs/testlog.txt

    - name: Install ffmpeg
      run: pip install ffmpeg

    - name: Install Meson
      run: pip install meson ninja

    - name: PKG_CONFIG_PATH
      shell: cmd
      run: |
        echo $PKG_CONFIG_PATH
        pkg-config --list-all
         
    - name: Setup Meson
      shell: cmd
      run: |
        # Open Visual Studio Command Prompt
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=x86
        meson setup builddir --backend=vs2019