 
name: 'tests Windows VS'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  windows:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2 
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: install dependencies
      shell: bash
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat -disableMetrics
        vcpkg install pthread:x86-windows-static
        find . -name '*.pthread'    
  