name: 'tests Windows MINGW64'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build_libs:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64 # Start a 64 bit Mingw environment
          update: true

      - name: Install dependencies
        run: |
          C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm --needed git make"
          C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm --needed mingw-w64-x86_64-{toolchain,ffmpeg}"
          C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm mingw-w64-x86_64-python3-pip"
          C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm --needed mingw-w64-x86_64-meson"

      - name: Setup
        shell: cmd
        run: |
          # Open Visual Studio Command Prompt Open x64 Native Tools Command Prompt for VS2019
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=x86
          $env:CHERE_INVOKING = 'yes'
          meson setup builddir --backend=vs
              
      - name: Build
        run: |
          $env:CHERE_INVOKING = 'yes'
          C:\msys64\usr\bin\bash -lc "meson compile -C builddir -v --backend=vs2019"

      - name: Test
        run: |
          $env:CHERE_INVOKING = 'yes' 
          C:\msys64\usr\bin\bash -lc "meson test -C builddir -v --backend=vs2019"
 