name: 'tests Windows VS'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build_libs:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2

      - name: Install dependencies
        run: |
          C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm --needed git make python3-pip ffmpeg meson"
          where ffmpeg

      - name: Setup
        run: |
          $env:CHERE_INVOKING = 'yes'
          C:\msys64\usr\bin\bash -lc "meson setup builddir -v --backend vs2019"