name: 'tests Windows VS'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  windows:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2 
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
 
    - name: install Clang
      run: |
        curl -fsSL -o LLVM10.exe https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/LLVM-10.0.0-win64.exe
        7z x LLVM10.exe -y -o"C:/Program Files/LLVM"
   