name: 'tests Windows'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build_libs:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
 
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Install Dependencies
      run: |
        pip install --upgrade meson

    - name: shellcheck
      run: |
        # This dir contains a pkg-config which meson will happily use and later fail, so remove it
        $env:path = ($env:path.Split(';') | Where-Object { $_ -ne 'C:\Strawberry\perl\bin' }) -join ';'
        meson --help