name: 'tests Windows VS'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build_libs:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2


      
      - name: Run a one-line script
        run: |
          ls
          ./windows.sh


          
