name: 'tests Windows'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build_libs:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

 
    - name: FFmpeg pc creation https://docs.conan.io/en/latest/reference/build_helpers/meson.html
      shell: cmd
      run: |
        pip3 install conan --upgrade
        pip3 install meson ninja
        conan remote add conan-sight https://conan.ircad.fr/artifactory/api/conan/sight
        where ffmpeg
        where pkg-config
        conan create . user/testing
        mkdir build && cd build 
        conan install ..
        where ffmpeg.pc
        conan build ..
        

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Windows_Meson_Testlog
        path: D:\a\sxplayer\sxplayer\build\meson-logs\meson-log.txt
