name: 'tests Windows VS'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  windows:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2

    - uses: msys2/setup-msys2@v2
 
    - name: install vcpkg
      shell: bash
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat -disableMetrics
        vcpkg install ffmpeg[ffmpeg,ffplay,nonfree,avresample]:x86-windows-static
        where pkg-config
        echo %PKG_CONFIG_PATH%
    