name: 'tests Windows'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build_libs:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - uses: msys2/setup-msys2@v2

    - name: install vcpkg
      shell: bash
      run: |
        echo "youyou"         
        set VCPKG_DEFAULT_TRIPLET=x64-windows      
        mkdir -p vcpkg2
        cd vcpkg2
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ls 
        ./bootstrap-vcpkg.bat -disableMetrics
        
        vcpkg install curl[ssl]:x86-windows
        vcpkg owns  curl 

    - uses: actions/upload-artifact@v1
      with:
        name: libcurl
        path: ./vcpkg2/vcpkg/installed/x86-windows/lib/pkgconfig/libcurl.pc

    - uses: actions/upload-artifact@v1
      with:
        name: libcurldebug
        path: ./vcpkg2/vcpkg/installed/x86-windows/debug/lib/pkgconfig/libcurl.pc
 