name: 'tests Windows'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build_libs:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
 

    - name: Install Dependencies
      run: |
        pip install --upgrade meson

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
        
    - name: shellcheck
      shell: cmd
      run: |
        meson setup builddir --backend vs