name: 'tests Windows'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build_libs:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Windows_Meson_Testlog
        path: build/meson-logs/testlog.txt

    - name: Install ffmpeg
      run: pip install ffmpeg

    - name: Install Meson
      run: pip install meson ninja

    - name: Setup Meson
      run: meson setup builddir --backend vs

    - name: test
      run: meson test -C builddir -v

             
      