name: 'tests Windows'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build_libs:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Windows_Meson_Testlog
        path: build/meson-logs/testlog.txt

    - name: Install Meson
      run: pip3 install -U meson ninja

    - name: ffmpeg with chocolate
      shell: cmd
      run: |
        choco install ffmpeg # Chocolatey is a package manager for Windows  build FFmpeg 
        ffmpeg --help
        where ffmpeg
       


    - name: PKG_CONFIG_PATH
      shell: cmd
      run: |
        where pkg-config
        ls -al C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\bin\
       