name: 'tests Windows VS'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  windows:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2 
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: msys2/setup-msys2@v2

    - name: install dependencies
      shell: bash
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat -disableMetrics
        vcpkg install ffmpeg[ffmpeg,ffplay,nonfree,avresample]:x86-windows-static      
        export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:D:\a\sxplayer\sxplayer\packages\ffmpeg_x86-windows-static\lib\pkgconfig
        set VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2019
        meson setup builddir --backend vs