name: 'tests Windows VS'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  windows_vs:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2 
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' 
        architecture: 'x64'
  

    - name: Setup
      shell: cmd
      run: |
        set VSCMD="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64"

    - name: Setup
      shell: cmd
      run: |
        VSCMD ^
        meson setup --help

    - name: Setup
      shell: cmd
      run: |
        VSCMD ^
        meson setup --help