name: 'tests Windows VS'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  windows:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2 
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: install dependencies
      shell: bash
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat -disableMetrics
        vcpkg install pthread:x32-windows ffmpeg[ffmpeg,ffplay,nonfree,avresample]:x32-windows
        pip install meson      
        vcpkg integrate install
        vcpkg integrate project
        vcpkg integrate remove       
        find . -name '*ffmpeg*'
        find . -name '*avcodec*'
        find . -name '*pthread*'
        find . -name '*.pc*'
        find . -name '*.include*'
        find . -name '*.lib*'
    - name: Setup
      shell: cmd
      run: | 
        set PKG_CONFIG_PATH=D:\a\sxplayer\sxplayer\vcpkg\installed\x32-windows\lib\pkgconfig;%PKG_CONFIG_PATH%
        "C:\Program Files (x32)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" && meson setup builddir --backend vs
  
    - name: BUILD
      shell: cmd
      run: |
        set PLATFORM="X32" 
        set INCLUDE=D:\a\sxplayer\sxplayer\vcpkg\installed\x32-windows\include;%INCLUDE%
        set LIB=D:\a\sxplayer\sxplayer\vcpkg\installed\x32-windows\lib;%LIB%
        set LIB=D:\a\sxplayer\sxplayer\vcpkg\packages\ffmpeg_x32-windows\lib;%LIB%
        "C:\Program Files (x32)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" && meson compile -C builddir -v 


    - name: TEST
      shell: cmd
      run: |
        meson test -C builddir