name: 'tests Windows'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build_libs:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Meson and ninja
      run: pip3 install -U meson ninja

    - name: Install Ffmpeg with Chocolatey (package manager for Windows)
      shell: cmd
      run: |
        choco install ffmpeg
        ffmpeg --help
        where ffmpeg
       
    - name: Install and configure vc-pkg
      shell: cmd
      run: |
        C:
        cd \
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg integrate install
        .\vcpkg install ffmpeg:x64-windows
